const nikeProducts = [
    { id: 1, name: "Nike Air Max 2021", category: "Shoes", image: "/images/Rectangle.png", availableColors: 5, price: "$150" },
    { id: 2, name: "Nike ZoomX Vaporfly NEXT%", category: "Shoes", image: "/images/Rectangle(1).png", availableColors: 3, price: "$250" },
    { id: 3, name: "Nike Air Force 1 PLT.AF.ORM", category: "shoes", image: "/images/Rectangle(2).png", availableColors: 4, price: "$65" },
    { id: 24, name: "Nike Air Max Plus", category: "Shoes", image: "/images/Rectangle(3).png", availableColors: 7, price: "$160" },
    { id: 5, name: "Nike Air Force 1", category: "Shoes", image: "/images/Rectangle(4).png", availableColors: 7, price: "$90" },
    { id: 25, name: "Nike Dri-FIT UV Hyverse", category: "Apparel", image: "/images/Rectangle(7).png", availableColors: 4, price: "$35" },
    { id: 6, name: "Nike React Infinity Run Flyknit", category: "Shoes", image: "/images/Rectangle(6).png", availableColors: 4, price: "$160" },
    { id: 4, name: "Nike Dri-FIT Mens T-Shirt", category: "Apparel", image: "/images/Rectangle(9).png", availableColors: 6, price: "$35" },
    { id: 7, name: "Nike Pro Training Shorts", category: "Apparel", image: "/images/Rectangle(28).png", availableColors: 3, price: "$45" },
    { id: 8, name: "Nike Air Max 97", category: "Shoes", image: "/images/Rectangle(20).png", availableColors: 2, price: "$170" },
    { id: 9, name: "Nike Air Zoom Pegasus 38", category: "Shoes", image: "/images/Rectangle(11).png", availableColors: 5, price: "$120" },
    { id: 10, name: "Nike Air Vapormax Flyknit 3", category: "Shoes", image: "/images/Rectangle(12).png", availableColors: 4, price: "$220" },
    { id: 11, name: "Nike Mercurial Superfly 8 Elite", category: "Shoes", image: "/images/Rectangle(22).png", availableColors: 3, price: "$275" },
    { id: 12, name: "Nike Zoom Freak 3", category: "Shoes", image: "/images/Rectangle(24).png", availableColors: 4, price: "$160" },
    { id: 13, name: "Nike Training T-Shirt", category: "Apparel", image: "/images/Rectangle(17).png", availableColors: 5, price: "$35" },
    { id: 14, name: "Nike Pro Hypercool Compression Shorts", category: "Apparel", image: "/images/Rectangle(25).png", availableColors: 4, price: "$40" },
    { id: 15, name: "Nike Air Max 90", category: "Shoes", image: "/images/Rectangle(16).png", availableColors: 6, price: "$120" },
    { id: 16, name: "Nike SB Dunk Low", category: "Shoes", image: "/images/Rectangle(15).png", availableColors: 3, price: "$110" },
    { id: 17, name: "Nike Blazer Mid 77", category: "Shoes", image: "/images/Rectangle(24).png", availableColors: 2, price: "$90" },
    { id: 18, name: "Nike React Element 55", category: "Shoes", image: "/images/Rectangle(18).png", availableColors: 5, price: "$130" },
    { id: 19, name: "Nike Dri-FIT AeroBill", category: "Accessories", image: "/images/Rectangle(34).png", availableColors: 4, price: "$70" },
    { id: 20, name: "Nike Air Zoom Terra Kiger 7", category: "Shoes", image: "/images/Rectangle(13).png", availableColors: 3, price: "$130" },
    { id: 21, name: "Nike Therma-FIT Hoodie", category: "Apparel", image: "/images/Rectangle(26).png", availableColors: 5, price: "$75" },
    { id: 22, name: "Nike Air Jordan 1 Retro", category: "Shoes", image: "/images/Rectangle(8).png", availableColors: 6, price: "$180" },
    { id: 23, name: "Nike Flex Run 2021", category: "Shoes", image: "/images/Rectangle(29).png", availableColors: 3, price: "$65" },
    { id: 26, name: "Nike Air Zoom Structure 24", category: "Shoes", image: "/images/Rectangle(30).png", availableColors: 4, price: "$130" },
    { id: 27, name: "Nike Lunar Epic Low Flyknit", category: "Shoes", image: "/images/Rectangle(31).png", availableColors: 5, price: "$160" },
    { id: 28, name: "Nike Air Max 270 React", category: "Shoes", image: "/images/Rectangle(32).png", availableColors: 3, price: "$150" },
    { id: 29, name: "Nike Training Backpack", category: "Accessories", image: "/images/Rectangle(27).png", availableColors: 3, price: "$50" },
    { id: 30, name: "Nike Tech Pack Sleeveless", category: "Apparel", image: "/images/Rectangle(23).png", availableColors: 4, price: "$100" },
  ];

  export default nikeProducts;